name: bloc_ffff
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  dio: ^5.3.3
  equatable: ^2.0.5
  retrofit: ^4.0.2
  get_it: ^7.6.4
  injectable: ^2.3.1
  dartz: ^0.10.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # retrofit_generator: ^8.0.0
  retrofit_generator:
    git:
      url: https://github.com/ho-doan/retrofit.dart.git
      path: generator
      ref: feature/generator-option-class-name
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  mocktail: ^1.0.1
  injectable_generator: ^2.4.0
  bloc_test: ^9.1.4
flutter:
  uses-material-design: true